INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1);
INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1);
INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1);
INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1);
INSERT INTO bases VALUES (null, "Retributor-Primer", "32mm", "Round", 32, 0, 1);
INSERT INTO bases VALUES (null, "Prussian Jaeger", "28mm", "Rectangle", 40, 20, 2);
INSERT INTO bases VALUES (null, "Prussian Jaeger", "28mm", "Rectangle", 40, 20, 2);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4);
INSERT INTO bases VALUES (null, "Prussian Command", "28mm", "Square", 40, 40, 3);


INSERT INTO tags VALUES (NULL, "storm sword", "weapon", 0);
INSERT INTO tags VALUES (NULL, "storm bow", "weapon", 0);
INSERT INTO tags VALUES (NULL, "rifle", "weapon", 0);
INSERT INTO tags VALUES (NULL, "musket", "weapon", 0);
INSERT INTO tags VALUES (NULL, "sword", "weapon", 0);
INSERT INTO tags VALUES (NULL, "armour", "equipment", 0);
INSERT INTO tags VALUES (NULL, "bedroll", "equipment", 0);
INSERT INTO tags VALUES (NULL, "forage bag", "equipment", 0);
INSERT INTO tags VALUES (NULL, "shako", "equpipment", 0);
INSERT INTO tags VALUES (NULL, "human", "affiliation", 0);
INSERT INTO tags VALUES (NULL, "sigmarite", "affiliation", 0);
INSERT INTO tags VALUES (NULL, "prussian", "affiliation", 0);
INSERT INTO tags VALUES (NULL, "napoleonic", "affiliation", 0);
INSERT INTO tags VALUES (NULL, "fantasy", "affiliation", 0);
INSERT INTO tags VALUES (NULL, "medieval", "affiliation", 0);
INSERT INTO tags VALUES (NULL, "silesian", "other", 0);