INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1, "Plastic", "", "Games Workshop", "Element Games", 0.0, CURRENT_DATE,  NULL, 1, 0, "not varnished", "AOS-Ret1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1, "Plastic", "", "Games Workshop", "Element Games", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "AOS-Ret1-2", 0, 0, 0);
INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1, "Plastic", "", "Games Workshop", "Element Games", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "AOS-Ret1-3", 0, 0, 0);
INSERT INTO bases VALUES (null, "Retributor", "32mm", "Round", 32, 0, 1, "Plastic", "", "Games Workshop", "Element Games", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "AOS-Ret1-4", 0, 0, 0);
INSERT INTO bases VALUES (null, "Retributor-Primer", "32mm", "Round", 32, 0, 1, "Plastic", "", "Games Workshop", "Element Games", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "AOS-Ret1-P", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Jaeger", "28mm", "Rectangle", 40, 20, 2, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Jaeger", "28mm", "Rectangle", 40, 20, 2, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Infantry", "28mm", "Square", 40, 40, 4, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);
INSERT INTO bases VALUES (null, "Prussian Command", "28mm", "Square", 40, 40, 3, "Plastic", "Alan Perry", "Perry Miniatures", "Perry Miniatures", 0.0, CURRENT_DATE, NULL, 1, 0, "not varnished", "PRU-Sil1-1", 0, 0, 0);


INSERT INTO tags VALUES (NULL, "sword");
INSERT INTO tags VALUES (NULL, "bow");
INSERT INTO tags VALUES (NULL, "rifle");
INSERT INTO tags VALUES (NULL, "musket");
INSERT INTO tags VALUES (NULL, "pistol");
INSERT INTO tags VALUES (NULL, "assault rifle");
INSERT INTO tags VALUES (NULL, "submachine gun");
INSERT INTO tags VALUES (NULL, "MG");
INSERT INTO tags VALUES (NULL, "bolt rifle");
INSERT INTO tags VALUES (NULL, "repeater");
INSERT INTO tags VALUES (NULL, "claws");
INSERT INTO tags VALUES (NULL, "spike");
INSERT INTO tags VALUES (NULL, "fangs");
INSERT INTO tags VALUES (NULL, "sword");
INSERT INTO tags VALUES (NULL, "spear");
INSERT INTO tags VALUES (NULL, "halberd");
INSERT INTO tags VALUES (NULL, "club");
INSERT INTO tags VALUES (NULL, "warhammer");
INSERT INTO tags VALUES (NULL, "dagger");
INSERT INTO tags VALUES (NULL, "staff");
INSERT INTO tags VALUES (NULL, "wand");
INSERT INTO tags VALUES (NULL, "light armour");
INSERT INTO tags VALUES (NULL, "leather armour");
INSERT INTO tags VALUES (NULL, "plate armour");
INSERT INTO tags VALUES (NULL, "cowl");
INSERT INTO tags VALUES (NULL, "robe");
INSERT INTO tags VALUES (NULL, "shako");
INSERT INTO tags VALUES (NULL, "helmet");
INSERT INTO tags VALUES (NULL, "bedroll");
INSERT INTO tags VALUES (NULL, "forage bag");
INSERT INTO tags VALUES (NULL, "musket pouch");
INSERT INTO tags VALUES (NULL, "lamp");
INSERT INTO tags VALUES (NULL, "torch");
INSERT INTO tags VALUES (NULL, "human");
INSERT INTO tags VALUES (NULL, "dwarf");
INSERT INTO tags VALUES (NULL, "troll");
INSERT INTO tags VALUES (NULL, "orc");
INSERT INTO tags VALUES (NULL, "snakeman");
INSERT INTO tags VALUES (NULL, "elf");
INSERT INTO tags VALUES (NULL, "prussian");
INSERT INTO tags VALUES (NULL, "french");
INSERT INTO tags VALUES (NULL, "british");
INSERT INTO tags VALUES (NULL, "austrian");
INSERT INTO tags VALUES (NULL, "russian");
INSERT INTO tags VALUES (NULL, "japanese");
INSERT INTO tags VALUES (NULL, "german");
INSERT INTO tags VALUES (NULL, "american");
INSERT INTO tags VALUES (NULL, "italian");
INSERT INTO tags VALUES (NULL, "fantasy");
INSERT INTO tags VALUES (NULL, "medieval");
INSERT INTO tags VALUES (NULL, "ww2");
INSERT INTO tags VALUES (NULL, "ww1");
INSERT INTO tags VALUES (NULL, "acw");
INSERT INTO tags VALUES (NULL, "awi");
INSERT INTO tags VALUES (NULL, "7yw");
INSERT INTO tags VALUES (NULL, "mounted");
INSERT INTO tags VALUES (NULL, "pet");
INSERT INTO tags VALUES (NULL, "dramatic");
INSERT INTO tags VALUES (NULL, "injured");

INSERT INTO storage VALUES (NULL, "Cardboard box", "1st shelf", 10, 0, 0, "Slightly damp");
INSERT INTO storage VALUES (NULL, "Warhammer", "Top shelf", 25, 1, 1, "Can fit one more 32mm base");
INSERT INTO storage VALUES (NULL, "Ancients", "Top shelf", 15, 1, 0, "");

INSERT INTO statuses VALUES (NULL, "New");
INSERT INTO statuses VALUES (NULL, "Built");
INSERT INTO statuses VALUES (NULL, "Undercoated");
INSERT INTO statuses VALUES (NULL, "Painted");
INSERT INTO statuses VALUES (NULL, "Varnished");
INSERT INTO statuses VALUES (NULL, "Complete");

INSERT INTO colours VALUES (NULL, "Mephiston Red", "Citadel", "Base Colors", "#991115", "");