name: Main Branch Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            coverage: linux-cov.xml
          - os: macos-latest
            coverage: macos-cov.xml
          - os: windows-latest
            coverage: windows-cov.xml
    env:
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup 'libxkbcommon-x11-0'
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pytest --cov=adjutant --cov-report xml:cov.xml --cov-fail-under=40 tests
      # - name: Run workflow tests
      #   run: |
      #     pytest tests/workflow
      - name: Check for issues
        run: |
          pylint -E adjutant
      - name: Validate formatting
        run: |
          black --check adjutant
      - uses: actions/upload-artifact@v2
        name: Upload coverage report for ${{matrix.os}}
        with:
          name: ${{matrix.coverage}}
          path: cov.xml
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            executable: adjutant-linux
            separator: ":"
          - os: macos-latest
            executable: adjutant-macos
            separator: ":"
          - os: windows-latest
            executable: adjutant-windows.exe
            separator: ";"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build executable
        run: |
          pyinstaller --icon=resources/icons/adjutant.ico --add-data "resources/${{matrix.separator}}resources/" --onefile --windowed --name ${{matrix.executable}} main.py
      - uses: actions/upload-artifact@v2
        name: Upload executable for ${{matrix.os}}
        with:
          name: ${{matrix.executable}}
          path: ./dist/${{matrix.executable}}
